services:
  db:
    image: postgres:15-alpine
    container_name: hackathon_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hackathon_db
    ports:
      - "5433:5432"
